### ISSUE TITLE
Particles-Editor

### ISSUE THREAD

**Issue by xxxLEOPARDxxx** [storm-devs/storm-engine#1]
Приветствую!
Меня интересует возможность в партикл-эдиторе назначить текстуру большего размера. Такое возможно? И как в целом это можно сделать?

**Comment by np-c0mp1ete** [comment]
Привет!
К сожалению, исходный код некоторых компонентов редактора частиц был утерян со временем. Поэтому мы пока не можем вносить изменения в инструменты из папки tools. У нас остались только уже собранные исполняемые файлы.

Hey!
Unfortunately, the source code for some of the particle editor components has been lost over time. Therefore, we cannot make changes to the tools from the 'tools' folder yet. We only have the compiled executables left.

**Comment by kk-se** [comment]
Привет,
может, этот код сохранится у кого-нибудь из бывших сотрудников компании Акелла? Думаю, что даже старшая версия является полезной.

Hi,
maybe that code is kept by some former employee of Akella company? I think that even older version is useful for us.

**Comment by np-c0mp1ete** [comment]
Да, было бы неплохо составить список утраченных компонентов для всех инструментов и попытаться связаться с их создателями.
**animation-view**: создан игроками, контактов автора нет
**modding-tool**: создан игроками, автор предположительно nathankell@piratesahoy.net. @kk-se, напишешь ему?
**model-view**: создан игроками, контактов автора нет
**particles-editor**: создан Акеллой, я обращусь к нашим контактам из числа бывших сотрудников
**scripts-hider**: больше не используется, нет смысла восстанавливать исходный код
**texture-converter**: создан игроками, контактов автора нет
**walk-patcher**: создан игроками, контактов автора нет

Yes, it would be a good idea to make a list of lost components for all tools and try to contact their creators.
**animation-view**: created by players, no contacts of the author
**modding-tool**: created by players, presumably nathankell@piratesahoy.net. @kk-se, could you contact him?
**model-view**: created by players, no contacts of the author
**particles-editor**: created by Akella, I will poke our contacts there
**scripts-hider**: no longer used, no point in restoring source code
**texture-converter**: created by players, no contacts of the author
**walk-patcher**: created by players, no contacts of the author

**Comment by kk-se** [comment]
Насколько я знаю, modding tool сделан нет г. Келлым, но другом членом Pirates Ahoy! – Инез Диас (Inez Dias). Поэтому, попытаю наладить связь с ней.

As far as I know, the modding tool was created not by Mr. Kell, but by another member of the Pirates Ahoy!, Inez Dias. Thus, I will try to make contact with her.

**Comment by xahon** [comment]
@np-c0mp1ete в каком смысле "создан игроками"? Игроки писали код для акеллы или акелла использовала любительские тулзы?

**Comment by xahon** [comment]
Проще, мне кажется, будет набабахать эти утилиты на каком-нибудь питоне, будет гораздо быстрее, чем переписывать их на C++. И сразу плюсик к кроссплатформе добавится

**Comment by np-c0mp1ete** [comment]
@xahon I'm sure Akella had proper game editors, but they weren't available to the modding community, so fans created their own tools. And now the tools developed by Akella are lost.

You're absolutely right about python. There are some tasks for creating tools in python on this [kanban board](https://github.com/storm-devs/storm-engine/projects/1).
