### ISSUE TITLE
Static initialization of non-trivial global objects

### ISSUE THREAD

**Issue by Hammie** [storm-devs/storm-engine#10]
We have multiple non-trivial static global variables that depend on each other, which causes issues because the order of initialization is not specified.

Currently my Release build crashes due to `core` being initialized before `fio`.

**Comment by espkk** [comment]
@Hammie, could you please check if it (specifically fio and core issue) is still present?

**Comment by Hammie** [comment]
The file system issue seems to be fixed for release builds, yes.

**Comment by espkk** [comment]
Thanks for the feedback! 
https://github.com/storm-devs/storm-engine/pull/56 should also fix it for CDebug
I leave this issue open to check for similar problems later
