### ISSUE TITLE
[BUG] Time is not accelerated after exiting dialogue

### ISSUE THREAD

**Issue by szymonj99** [storm-devs/storm-engine#148]
**Describe the bug**
The time acceleration is turned off when entering dialogue, but isn't enabled when dialogue stops. Pressing the `r` key to change time acceleration says that the acceleration is turned off, even though it was turned off by the dialogue already, meaning the `r` key has to be pressed twice to re-activate time acceleration

**To Reproduce**
1. Start a new game
2. Talk to the first NPC
3. When following the NPC, press `r` to speed up time.
4. When entering dialogue with the NPC, time acceleration will stop. Press `r` key twice to activate time acceleration again.

**Expected behavior**
When exiting the dialogue, time acceleration should be activated again or the `r` key would activate time acceleration on the first key press.

**Comment by Hammie** [comment]
What game were you playing?

I may be wrong but I think time acceleration is handled mostly through the game scripts. So we would have to fix it in the specific game/mod.

**Comment by szymonj99** [comment]
I was playing Sea Dogs - To Each His Own.

**Comment by szymonj99** [comment]
Apparently fixed here: https://github.com/storm-devs/sd-teho-public/pull/11
Closing.
