### ISSUE TITLE
Write a python script to convert gm files to obj

### ISSUE THREAD

**Issue by MangioneAndrea** [storm-devs/storm-engine#16]
https://github.com/storm-devs/storm-engine/blob/5349ef2c0bb8fc8b2cf43d39ff50555950076bf5/src/libs/Geometry/geom_static.cpp#L20

https://github.com/storm-devs/seadogs-file-formats

**Comment by np-c0mp1ete** [comment]
Implemented in https://github.com/storm-devs/storm-engine/pull/17
