### ISSUE TITLE
Bincrafters are gone but still referenced in conanfile.py

### ISSUE THREAD

**Issue by xahon** [storm-devs/storm-engine#232]
https://github.com/storm-devs/storm-engine/blob/724d2e8c86fd266a7913dfc77c71875101892f0f/conanfile.py#L18-L19
Bincrafters is deprecated remote but still available to fetch packages from it. I wouldn't count on it because it can get unreachable someday

**Comment by espkk** [comment]
> 
> 
> https://github.com/storm-devs/storm-engine/blob/724d2e8c86fd266a7913dfc77c71875101892f0f/conanfile.py#L18-L19
> 
> Bincrafters is deprecated remote but still available to fetch packages from it. I wouldn't count on it because it can get unreachable someday

I cannot find any info regarding that
it recently moved to https://bincrafters.jfrog.io/artifactory/api/conan/public-conan but we already updated the path
