### ISSUE TITLE
C++ standard

### ISSUE THREAD

**Issue by egorpugin** [storm-devs/storm-engine#31]
If this repo is built with the latest VS, please consider choosing C++17 or even C++20 standard.
You'll get a lot of potential code upgrades with reduced possibility of bugs/issues.
Modern code is easier to maintain as well.

**Comment by np-c0mp1ete** [comment]
@egorpugin That's already the case. https://github.com/storm-devs/storm-engine/blob/develop/src/CMakeLists.txt#L16

**Comment by egorpugin** [comment]
Oh, indeed, sorry.
Can you put a small note into readme?
Something like `Storm Engine uses the latest C++ standard.`
or
Something like `Storm Engine uses C++20.`
