### ISSUE TITLE
Connecting alpha textures to characters

### ISSUE THREAD

**Issue by Shomka4ert** [storm-devs/storm-engine#33]
Hey, guys. 
Need to connect the use of alpha textures to the characters, so that you can make more realistic hair, as well as belts.
I hope that there will be those who want to solve this issue.
Thanks!

**Comment by Artess999** [comment]
> Hey, guys.
> Need to connect the use of alpha textures to the characters, so that you can make more realistic hair, as well as belts.
> I hope that there will be those who want to solve this issue.
> Thanks!

Hi!
Sorry for late answer - if you want to use alpha on characters, you should replace technique Animation in animation.fx with 
```
technique Animation
{
    pass p0
    {
        Lighting = true;

        ColorOp[0] = modulate2x;
        ColorOp[1] = disable;

        AlphaOp[0] = disable;

        AlphaTestEnable = true;
        AlphaBlendEnable = false;
        
        AlphaOp[0] = modulate;
        AlphaArg1[0] = texture;
        AlphaArg2[0] = current;
    }
}
```

(https://github.com/storm-devs/storm-engine/blob/develop/src/techniques/animation.fx)

<img width="433" alt="2021-08-01_16 47 15" src="https://user-images.githubusercontent.com/25062433/127784786-97337867-f24b-4f39-b855-ce6500263492.png">
