### ISSUE TITLE
Convert Float to String

### ISSUE THREAD

**Issue by MrMyth** [storm-devs/storm-engine#428]
Good afternoon. Please add a function to translate floating values into text. Scripts have a similar function, but it rounds the value and discards the final numbers. The kernel has a translation of a variable into a floating value. Now I need a function that does the opposite. Thank you.

**Comment by Hammie** [comment]
You want a function to convert a floating point number into a string, and `"" + myFloat` is not working?

I'm guessing you'll want more control over the precision of the final text?

Something like this: 
```
string floatToString(float value, number precision);
```

**Comment by MrMyth** [comment]
I have already solved the problem
string ConvertToText (float valve)
{
return ""+valve;	
}
