### ISSUE TITLE
[BUG] SoundService::GetRandomName

### ISSUE THREAD

**Issue by Artess999** [storm-devs/storm-engine#434]
Looks like there's a bug in SoundService::GetRandomName
If there are more than 2 tracks in a section, the first one is never played
e.g. music_alias.ini in COAS
```
[music_shop]
prior = 192
name = MUSIC\07-Town.ogg
name = MUSIC\11-Town2.ogg
```

MUSIC\07-Town.ogg is never playing

FYI: as I know, it was fixed in DMC

**Comment by espkk** [comment]
should be fixed with #449
