### ISSUE TITLE
[BUG] EqMultiply(const CMatrix &m1, const CMatrix &m2) can be called with invalid m1 matrix

### ISSUE THREAD

**Issue by xakod** [storm-devs/storm-engine#513]
**Describe the bug**
inline void CMatrix::EqMultiply(const CMatrix &m1, const CMatrix &m2) can be called with invalid m1 matrix
**To Reproduce**
1. I just build the latest commit from develop
2. Use resources from sd-teho-public/develop-rus
3. Start executable from vs or not

**Expected behavior**
No access violation 

**Screenshots**

**Additional context**
Dump https://drive.google.com/file/d/1fCB38Vgj_xGfKV40thK0qDD7U9jXjLnI/view?usp=sharing

**Comment by espkk** [comment]
Can you provide more context? Also, to open the dump file I need `engine.exe` and `engine.pdb` which you used to create the dump

**Comment by xakod** [comment]
Sorry, I packed everything now https://drive.google.com/file/d/1MjfWXb0u2k_dFlhU77THsTZSZdV2rCic/view?usp=sharing
Maybe I have a problem with my enviroment/system or smth like that because I see the same error with beta4

**Comment by espkk** [comment]
> Sorry, I packed everything now https://drive.google.com/file/d/1MjfWXb0u2k_dFlhU77THsTZSZdV2rCic/view?usp=sharing Maybe I have a problem with my enviroment/system or smth like that because I see the same error with beta4

Most likely the script code is not updated for the engine code. AFAIK, it's not open-source anymore. There are a few alternatives though e.g. https://github.com/PiratesAhoy/new-horizons

**Comment by espkk** [comment]
From what I see in the dump it's actually most likely that you don't have the required resources. For `sd-teho-public` there are no resources available for free. You have to buy the game to get them and use a specific version of it. A better choice would be to get other resources. These are some discord servers with free mods for this engine:
https://discord.gg/Mp8mMvMK
https://discord.gg/Z6ujph7Y
https://discord.gg/ypCA3BG2
https://discord.gg/HtgzZjDq

**Comment by xakod** [comment]
Ok, thank you!
