### ISSUE TITLE
Restore the logic of vanilla CoAS MSGIDs

### ISSUE THREAD

**Issue by espkk** [storm-devs/storm-engine#8]
Some messages had been changed during TEHO development. For consistency, they shall be reverted. If some logic is used in TEHO it shall be moved to newly created MSGIDs which shall not intersect with the original ones.

**Comment by Hammie** [comment]
I believe this should be completed now?

**Comment by espkk** [comment]
> I believe this should be completed now?

Do we have a list of events/msgs that use compatibility layer?
