### ISSUE TITLE
[BUG] Game needs to be restarted to reload interface configuration

### ISSUE THREAD

**Issue by Hammie** [storm-devs/storm-engine#89]
**Describe the bug**
The game does not reload the interface ini files.

**To Reproduce**
1. Start the game
2. Edit some interface ini file
3. Close and reopen the relevant interface
4. Interface does not reflect changed config

**Expected behavior**
The game should reload the ini file and show the interface with the changed config

**Additional context**
In the past the game reloaded interface configs every time the interface was openend. A better solution might be to make this behavior configurable or possibly use a debug key to reload ini files.

**Comment by Hammie** [comment]
Bug was introduced by https://github.com/storm-devs/storm-engine/commit/7bc02807f7dddbd9aa03ef3fb022c82be6d2e5f0#diff-c47bce051f28da6d01565cc09ad529b745ae99fd55f1637388a2db5888ac3703L313

**Comment by espkk** [comment]
Should be fixed now
