### ISSUE TITLE
[BUG] Static analyzer found bugs.

### ISSUE THREAD

**Issue by KurenevAlexandr** [storm-devs/storm-engine#98]
I checked your project with the PVS-Studio static analyzer. 

Some analyzer warnings seemed interesting to me, so I wrote an article about them: https://habr.com/ru/company/pvs-studio/blog/564698/. I think it will be useful to you. 

Part of the warnings pointed to lines of code marked with special comments. Seems like you are aware of problems in your code. 

Note. As open project developers, you can use one of free licensing options. If you find the analyzer interesting, you can use it regularly. Ways to Get a Free PVS-Studio License: https://pvs-studio.com/en/blog/posts/0614/

**Comment by np-c0mp1ete** [comment]
@KurenevAlexandr, thanks a lot for reviewing our project!

We'll definitely pay attention to the found issues in the near future.
Adding static code analysis to our CI pipeline is also on our to-do list.

Thanks again for the report!

**Comment by espkk** [comment]
> I checked your project with the PVS-Studio static analyzer. 
> 
> Some analyzer warnings seemed interesting to me, so I wrote an article about them: https://habr.com/ru/company/pvs-studio/blog/564698/. I think it will be useful to you. 
> 
> Part of the warnings pointed to lines of code marked with special comments. Seems like you are aware of problems in your code. 
> 
> Note. As open project developers, you can use one of free licensing options. If you find the analyzer interesting, you can use it regularly. Ways to Get a Free PVS-Studio License: https://pvs-studio.com/en/blog/posts/0614/ 
> 
>  

Thanks for noticing us 🙂
Actually, I made plenty of critical SCA fixes back in the days, so the most issues from the original (the state in that we got the engine) engine had gone.
Indeed, I marked down many non-critical issues and almost ignored minor ones.
Also, most issues from the article come from recent commits.
That is probably a good reason to think about integrating SCA into the pipeline :)
I'm sure we will come back to it and consider using PVS-Studio after solving more important problems that affect the whole project

**Comment by espkk** [comment]
I've looked through it again. Most of the alarms don't affect the code or need more complex solution. But there are some useful ones as well, I'll take care of them so I'm closing this for now. Thanks once again.

P.S. it's a bit weird that PVS-Studio treats srv.malloc as std::malloc. I'm wondering if it was done intentionally, but that's a bit confusing considering the fact it uses `new` internally
